rubocop:
  image: ruby:2.5
  script:
    - gem install rubocop --no-ri --no-rdoc
    - rubocop

.rspec_default: &rspec_default
  before_script:
    - ruby -v
    - gem install bundler --no-ri --no-rdoc
    - export BUNDLE_GEMFILE="spec/gemfiles/${RSPEC_GEMFILE}"
    - echo $BUNDLE_GEMFILE
    - bundle install --jobs=$(nproc) --path="../../cache/bundle"
    - bundle list
  script:
    - bundle exec rake spec
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - cache/

rspec-ruby2.4.4-rails4.0:
  <<: *rspec_default
  image: ruby:2.4.4
  variables:
    RSPEC_GEMFILE: rails40

rspec-ruby2.5.1-rails4.0:
  <<: *rspec_default
  image: ruby:2.5.1
  variables:
    RSPEC_GEMFILE: rails40

rspec-ruby2.3.7-rails4.1:
  <<: *rspec_default
  image: ruby:2.3.7
  variables:
    RSPEC_GEMFILE: rails41

rspec-ruby2.4.4-rails4.1:
  <<: *rspec_default
  image: ruby:2.4.4
  variables:
    RSPEC_GEMFILE: rails41

rspec-ruby2.5.1-rails4.1:
  <<: *rspec_default
  image: ruby:2.5.1
  variables:
    RSPEC_GEMFILE: rails41

rspec-ruby2.3.7-rails4.2:
  <<: *rspec_default
  image: ruby:2.3.7
  variables:
    RSPEC_GEMFILE: rails42

rspec-ruby2.4.4-rails4.2:
  <<: *rspec_default
  image: ruby:2.4.4
  variables:
    RSPEC_GEMFILE: rails42

rspec-ruby2.5.1-rails4.2:
  <<: *rspec_default
  image: ruby:2.5.1
  variables:
    RSPEC_GEMFILE: rails42

rspec-ruby2.3.7-rails5.0:
  <<: *rspec_default
  image: ruby:2.3.7
  variables:
    RSPEC_GEMFILE: rails50

rspec-ruby2.4.4-rails5.0:
  <<: *rspec_default
  image: ruby:2.4.4
  variables:
    RSPEC_GEMFILE: rails50

rspec-ruby2.5.1-rails5.0:
  <<: *rspec_default
  image: ruby:2.5.1
  variables:
    RSPEC_GEMFILE: rails50

rspec-ruby2.3.7-rails5.1:
  <<: *rspec_default
  image: ruby:2.3.7
  variables:
    RSPEC_GEMFILE: rails51

rspec-ruby2.4.4-rails5.1:
  <<: *rspec_default
  image: ruby:2.4.4
  variables:
    RSPEC_GEMFILE: rails51

rspec-ruby2.5.1-rails5.1:
  <<: *rspec_default
  image: ruby:2.5.1
  variables:
    RSPEC_GEMFILE: rails51
