stages:
  - security
  - build
  - test
  - codequality
  - release

sast:
  stage: security

dependency_scanning:
  stage: security

secret_detection:
  stage: security

build:
  stage: build
  image: ruby:2.6
  script:
    - gem install bundler --no-document
    - bundle update
  artifacts:
    paths:
      - Gemfile.lock

.rspec: &rspec
  stage: test
  before_script:
    - ruby -v
    - echo "${RSPEC_RAILS_VERSION}"
    - gem install bundler -v "~>${BUNDLER_VERSION:-2.0}" --no-document
    - export BUNDLE_GEMFILE="spec/Gemfile"
    - bundle install --jobs=$(nproc) --path="../cache/bundle"
    - bundle list
  script:
    - bundle exec rake spec
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - cache/

rspec-ruby2.5-rails5.0:
  <<: *rspec
  image: ruby:2.5
  variables:
    RSPEC_RAILS_VERSION: "5.0"

rspec-ruby2.6-rails5.0:
  <<: *rspec
  image: ruby:2.6
  variables:
    RSPEC_RAILS_VERSION: "5.0"

rspec-ruby2.5-rails5.1:
  <<: *rspec
  image: ruby:2.5
  variables:
    RSPEC_RAILS_VERSION: "5.1"

rspec-ruby2.6-rails5.1:
  <<: *rspec
  image: ruby:2.6
  variables:
    RSPEC_RAILS_VERSION: "5.1"

rspec-ruby2.5-rails5.2:
  <<: *rspec
  image: ruby:2.5
  variables:
    RSPEC_RAILS_VERSION: "5.2"

rspec-ruby2.6-rails5.2:
  <<: *rspec
  image: ruby:2.6
  variables:
    RSPEC_RAILS_VERSION: "5.2"

rspec-ruby2.5-rails6.0:
  <<: *rspec
  image: ruby:2.5
  variables:
    RSPEC_RAILS_VERSION: "6.0"

rspec-ruby2.6-rails6.0:
  <<: *rspec
  image: ruby:2.6
  variables:
    RSPEC_RAILS_VERSION: "6.0"

rspec-ruby2.5-rails6.1:
  <<: *rspec
  image: ruby:2.5
  variables:
    RSPEC_RAILS_VERSION: "6.1"

rspec-ruby2.6-rails6.1:
  <<: *rspec
  image: ruby:2.6
  variables:
    RSPEC_RAILS_VERSION: "6.1"

rspec-ruby2.7-rails7.0:
  <<: *rspec
  image: ruby:2.7
  variables:
    RSPEC_RAILS_VERSION: "7.0"

rspec-ruby3.0-rails7.0:
  <<: *rspec
  image: ruby:3.0
  variables:
    RSPEC_RAILS_VERSION: "7.0"

rubocop:
  stage: codequality
  image: ruby:2.6
  script:
    - gem install rubocop rubocop-performance --no-document
    - rubocop

release:
  stage: release
  image: ruby:3.0
  script:
    - gem install bundler --no-document
    - bundle update
    - rake release
  only:
    - tags
