require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.0
  NewCops: disable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - 'lib/rails-menu-manager.rb'

RSpec/MultipleExpectations:
  Max: 3