require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.4

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Metrics/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - 'lib/rails-menu-manager.rb'
