require:
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - 'lib/rails-menu-manager.rb'
