sudo: false

language: ruby

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0

gemfile:
  - gemfiles/rails40
  - gemfiles/rails41
  - gemfiles/rails42
  - gemfiles/rails50
  - gemfiles/rails51

matrix:
  exclude:
    - rvm: 2.2.9
      gemfile: gemfiles/rails50
    - rvm: 2.2.9
      gemfile: gemfiles/rails51

script: bundle exec rake spec

before_install:
  - gem install bundler -v '~> 1.16'
