# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in rails-menu-manager.gemspec
gemspec path: '../..'

gem 'railties', "~> #{ENV.fetch('RSPEC_RAILS_VERSION')}"
